version: "3.9"

services:
    db:
        image: postgres
        environment:
            - "POSTGRES_USER=postgres"
            - "POSTGRES_PASSWORD=postgres"
            - "POSTGRES_DB=ACME"
        ports:
            - "5432:5432"
    backend:
        build: ./backend
        ports:
            - "3000:3000"
        depends_on:
            - db
    frontend:
        build: ./frontend
        ports:
            - "8080:8080"
        depends_on:
            - backend
    

  